### ISSUE TITLE
ImportError: No module named plugins.lookup

### ISSUE THREAD

**Issue by shencan** [jonhadfield/ansible-lookups#1]
When I use ansible-lookups script import modules   found  can not import LookupBase ,
ansible version: `1.9.1`
run command: 

``` shell
In [24]: from ansible.plugins.lookup import LookupBase
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-24-bdfd61f23b01> in <module>()
----> 1 from ansible.plugins.lookup import LookupBase

ImportError: No module named plugins.lookup
```

**Comment by jonhadfield** [comment]
I've only tested these against devel (2.0.0) and the modules I rely on aren't in the 1.x series.
Will see if I can make them compatible with both, or at least add a set that will work with 1.x.

**Comment by jonhadfield** [comment]
I've restructured the repo with ansible 1.9 compatible plugins in the v1 folder.
