### ISSUE TITLE
aws_ec2_instance_id_from_name can return id of a terminated instance

### ISSUE THREAD

**Issue by windowsrefund** [jonhadfield/ansible-lookups#2]
In my case, I'd like to grab the id of an instance only when it is found to be in a running state. Wondering if it's possible to add some kind of flag which would affect the functionality of the lookup...

**Comment by jonhadfield** [comment]
What's your use case? 
If you only want to run a task if an instance is running, then you could use 'aws_ec2_instance_id_from_name' to get the id and add a 'when' statement that checks that 'aws_ec2_instance_status_from_name' returns 'running'.

**Comment by windowsrefund** [comment]
thanks, playing with this now...

**Comment by jonhadfield** [comment]
Closing. Please re-open if you still have an issue.
